#pragma once

#define REFLECTIVE_FUNCTION "?ReflectiveStub@@YA_NXZ"
#define DLL_MITIGATION_POLICY PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON
#define RTL_USER_PROC_PARAMS_NORMALIZED 0x00000001
#define PROCESS_CREATE_FLAGS_SUSPENDED 0x00000200		//Only for NtCreateUserProcess
#define THREAD_CREATE_FLAGS_CREATE_SUSPENDED 0x00000001
#define INDEX_IMAGENAME 0 
#define INDEX_COMMANDLINE 1 
#define INDEX_CURRENT_DIRECTORY 2
#define STATUS_HASHES_NOT_RESOLVED (NTSTATUS)0x42069
#define STATUS_HASH_DOES_NOT_EXIST (NTSTATUS)0x6969
#define STATUS_IDS_FUNCTION_NOT_FOUND (NTSTATUS)0xbabecafe
#define STATUS_FUNCTION_PTR_NOT_FOUND (NTSTATUS)0xdeadbeef